# Generated by Django 3.0.3 on 2020-02-24 23:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shortener', '0002_auto_20200223_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturl',
            name='update',
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
